export const ADD_GOAL = 'ADD_GOAL';
export const REMOVE_GOAL = 'REMOVE_GOAL';
export const RETRIEVE_GOALS = 'RETRIEVE_GOALS';
export const SET_WORK_TIME = 'SET_WORK_TIME';
export const SEND_RECORDS = 'SEND_RECORDS';
export const RETRIEVE_POMODORI = 'RETRIEVE_POMODORI';
export const DELETE_POMODRO = 'DELETE_POMODORO';